sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
  - npm run install-themes
  - rm -f ./themes/hexo-theme-matery/_config.yml
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages
  verbose: true
  deployment_file: true

